=== magnibruno/MacmillanJSONFiles/.grammar.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "book": {
      "type": "string"
    },
    "CEFRLevel": {
      "type": "string"
    },
    "dialect": {
      "type": "string"
    },
    "chapter": {
      "type": "object",
      "properties": {
        "chapterUnit": {
          "type": "string"
        },
        "chapterTitle": {
          "type": "string"
        },
        "chapterQuote": {
          "type": "string"
        },
        "chapterFrontImage": {
          "type": "string"
        },
        "chapterObjectives": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "sectionNumber": {
                "type": "number"
              },
              "sectionTitle": {
                "type": "string"
              },
              "sectionObjective": {
                "type": "string"
              },
              "GKU": {
                "type": "string"
              },
              "sectionSkills": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "skillType": {
                      "type": "string"
                    },
                    "skillName": {
                      "type": "string"
                    },
                    "skillTitle": {
                      "type": "string"
                    }
                  },
                  "required": ["skillType", "skillName", "skillTitle"]
                }
              },
              "sectionPart": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "partTitle": {
                      "type": "string"
                    },
                    "partImage": {
                      "type": "string"
                    },
                    "partSubTitle": {
                      "type": "string"
                    },
                    "textContents": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "paragraphOrdinal": {
                            "type": "number"
                          },
                          "paragraphTitle": {
                            "type": "string"
                          },
                          "paragraphSubtitles": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          "paragraphContents": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          }
                        },
                        "required": ["paragraphOrdinal", "paragraphTitle", "paragraphSubtitles", "paragraphContents"]
                      }
                    },
                    "sets": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "setMarker": {
                            "type": "string"
                          },
                          "setHeading": {
                            "type": "string"
                          },
                          "setImage": {
                            "type": ["string", "null"]
                          },
                          "setAudioNumber": {
                            "type": ["number", "null"]
                          },
                          "setIgnore": {
                            "type": "boolean"
                          },
                          "grammarHub": {
                            "type": "boolean"
                          },
                          "exerciseType": {
                            "type": ["string", "null"]
                          },
                          "exerciseInstruction": {
                            "type": "string"
                          },
                          "exercises": {
                            "type": ["array", "null"],
                            "items": {
                              "type": "object",
                              "properties": {
                                "exerciseSentences": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "sentenceOrdinal": {
                                        "type": "number"
                                      },
                                      "sentences": {
                                        "type": "array",
                                        "items": {
                                          "type": "string"
                                        }
                                      },
                                      "blankedWords": {
                                        "type": "array",
                                        "items": {
                                          "type": ["string", "number"]
                                        }
                                      }
                                    },
                                    "required": ["sentenceOrdinal", "sentences", "blankedWords"]
                                  }
                                },
                                "exerciseQuestion": {
                                  "type": ["string", "null"]
                                },
                                "exerciseMaxAnswer": {
                                  "type": ["number", "null"]
                                },
                                "exerciseMinAnswer": {
                                  "type": ["number", "null"]
                                },
                                "exerciseAnswers": {
                                  "type": ["string", "null"]
                                },
                                "LKUs": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "context": {
                                  "type": "string"
                                }
                              },
                              "required": ["exerciseSentences"]
                            }
                          },
                          "wordBank": {
                            "type": ["array", "null"],
                            "items": {
                              "type": "string"
                            }
                          },
                          "textContents": {
                            "type": ["array", "null"],
                            "items": {
                              "type": "object",
                              "properties": {
                                "paragraphOrdinal": {
                                  "type": "number"
                                },
                                "paragraphTitle": {
                                  "type": "string"
                                },
                                "paragraphSubtitles": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "paragraphContents": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                }
                              },
                              "required": ["paragraphOrdinal", "paragraphTitle", "paragraphSubtitles", "paragraphContents"]
                            }
                          }
                        },
                        "required": ["setMarker", "setIgnore", "exerciseInstruction"]
                      }
                    }
                  },
                  "required": ["partTitle", "partImage", "partSubTitle", "sets"]
                }
              }
            },
            "required": ["sectionNumber", "sectionTitle", "sectionObjective", "GKU", "sectionSkills", "sectionPart"]
          }
        }
      },
      "required": ["chapterUnit", "chapterTitle", "chapterQuote", "chapterFrontImage", "chapterObjectives", "sections"]
    }
  },
  "required": ["book", "CEFRLevel", "dialect", "chapter"]
}

=== magnibruno/MacmillanJSONFiles/validatedJSONContent/A1Unit1Grammar.valid.json
{
	"book": "Language Hub",
	"CEFRLevel": "A1",
	"dialect": "American",
	"chapter": {
		"chapterUnit": "1",
		"chapterTitle": "Nice to meet you!",
		"chapterQuote": "The language of friendship is not words but meanings. Henry David Thoreau",
		"chapterFrontImage": "",
		"chapterObjectives": [
			"talk about where you're from'",
			"introduce a friend",
			"greet people",
			"fill in a form"
		],
		"sections": [
			{
				"sectionNumber": 1.1,
				"sectionTitle": "Say hello",
				"sectionObjective": "Talk about where you're from",
				"GKU": "Language_Hub_A1_Unit1_Lesson1_2",
				"sectionSkills": [
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "countries"
					},
					{
						"skillType": "P",
						"skillName": "Pronunciation",
						"skillTitle": "syllables and syllable stress"
					},
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "numbers 0-10"
					},
					{
						"skillType": "G",
						"skillName": "Grammar",
						"skillTitle": "present simple be: I, you"
					}
				],
				"sectionPart": [
					{
						"partTitle": "GRAMMAR",
						"partImage": "",
						"partSubTitle": "Simple present be: I, you",
						"textContents": [],
						"sets": [
							{
								"setMarker": "A",
								"setHeading": "",
								"setImage": null,
								"setAudioNumber": 1.6,
								"setIgnore": true,
								"grammarHub": false,
								"exerciseType": "TSS dictate",
								"exerciseInstruction": "Listen to the examples. Underline the verbs.",
								"exercises": [
									{
										"exerciseSentences": [
											{
												"sentenceOrdinal": 1,
												"sentences": [
													"I’m from Spain."
												],
												"blankedWords": [
													1
												]
											},
											{
												"sentenceOrdinal": 2,
												"sentences": [
													"Are you from Madrid?"
												],
												"blankedWords": [
													1
												]
											},
											{
												"sentenceOrdinal": 3,
												"sentences": [
													"No, I’m not. I’m from Bilbao."
												],
												"blankedWords": [
													2
												]
											}
										]
									}
								]
							},
							{
								"setMarker": "B",
								"setHeading": "WORK IT OUT",
								"setImage": null,
								"setAudioNumber": null,
								"setIgnore": true,
								"exerciseType": "word bank",
								"textMode": "full article",
								"exerciseInstruction": "Circle the correct verb.",
								"textContents": [
									{
										"paragraphOrdinal": 1,
										"paragraphTitle": "WORK IT OUT",
										"paragraphSubtitles": [
											"am/are"
										],
										"paragraphContents": [
											"I'm from Spain.",
											"You're from Turkey.",
											"I'm not from New York.",
											"You're not from Toronto.",
											"Are you from Brazil? No, I'm not."
										]
									}
								],
								"exercisesWordBank": [
									{
										"sentenceOrdinal": 1,
										"exerciseQuestion": null,
										"exerciseMaxAnswer": null,
										"exerciseMinAnswer": null,
										"exerciseAnswers": "",
										"blankedWords": [
											1,
											12,
											13,
											16
										],
										"LKUs": [
											"be"
										],
										"context": "textContents"
									}
								]
							},
							{
								"setMarker": "C",
								"setHeading": "",
								"setImage": null,
								"setAudioNumber": null,
								"setIgnore": false,
								"grammarHub": true,
								"exerciseType": "Grammar SB/without explanation",
								"exerciseInstruction": "Complete the conversations with the words in the box.",
								"wordBank": [
									"am",
									"are",
									"I",
									"I'm",
									"no",
									"not",
									"yes",
									"you"
								],
								"exercises": [
									{
										"exerciseSentences": [
											{
												"sentenceOrdinal": 1,
												"sentences": [
													"A: Are you from Italy?",
													"B: Yes, I am."
												],
												"blankedWords": [
													"Are"
												]
											},
											{
												"sentenceOrdinal": 2,
												"sentences": [
													"A: Hello. Are you from Brazil?",
													"B: Yes, I am."
												],
												"blankedWords": [
													"am"
												]
											},
											{
												"sentenceOrdinal": 3,
												"sentences": [
													"A: Are you from Australia?",
													"B: Yes, I am."
												],
												"blankedWords": [
													"you"
												]
											},
											{
												"sentenceOrdinal": 4,
												"sentences": [
													"A: Are you from Morocco?",
													"B: Yes, I am."
												],
												"blankedWords": [
													"Yes"
												]
											},
											{
												"sentenceOrdinal": 5,
												"sentences": [
													"A: Are you from Canada?",
													"B: No, I’m not."
												],
												"blankedWords": [
													"No"
												]
											},
											{
												"sentenceOrdinal": 6,
												"sentences": [
													"A: Good morning. Are you from Argentina?",
													"B: Yes, I am."
												],
												"blankedWords": [
													"I"
												]
											},
											{
												"sentenceOrdinal": 7,
												"sentences": [
													"A: Hello Lisa. Are you from China?",
													"B: No, I’m not."
												],
												"blankedWords": [
													"No"
												]
											},
											{
												"sentenceOrdinal": 8,
												"sentences": [
													"A: Are you from Mexico?",
													"B: No, I'm not."
												],
												"blankedWords": [
													"I'm"
												]
											}
										]
									}
								]
							}
						]
					}
				]
			},
			{
				"sectionNumber": 1.2,
				"sectionTitle": "What’s your job?",
				"sectionObjective": "Introduce a friend",
				"GKU": "Language_Hub_A1_Unit1_Lesson1_2",
				"sectionSkills": [
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "jobs"
					},
					{
						"skillType": "S",
						"skillName": "Reading",
						"skillTitle": "identifying personal pronouns"
					},
					{
						"skillType": "G",
						"skillName": "Grammar",
						"skillTitle": "simple present be: he, she, it"
					},
					{
						"skillType": "P",
						"skillName": "Pronunciation",
						"skillTitle": "contractions with be"
					}
				],
				"sectionPart": [
					{
						"partTitle": "GRAMMAR",
						"partImage": "",
						"partSubTitle": "Simple present be: he, she, it",
						"sets": [
							{
								"setMarker": "A",
								"setHeading": "",
								"setImage": null,
								"setAudioNumber": null,
								"setIgnore": false,
								"grammarHub": false,
								"exerciseType": "Grammar SB/without explanation",
								"exerciseInstruction": "Read the examples from the emails. Underline the verbs.",
								"exerciseExample": null,
								"wordBank": [
									"It's",
									"isn't",
									"is",
									"How's"
								],
								"exercises": [
									{
										"exerciseSentences": [
											{
												"sentenceOrdinal": 1,
												"sentences": [
													"It's a small team with five people."
												],
												"blankedWords": [
													"It's"
												]
											},
											{
												"sentenceOrdinal": 2,
												"sentences": [
													"My manager isn't very friendly, but she's OK."
												],
												"blankedWords": [
													"isn't"
												]
											},
											{
												"sentenceOrdinal": 3,
												"sentences": [
													"My colleague Anton is nice."
												],
												"blankedWords": [
													"is"
												]
											},
											{
												"sentenceOrdinal": 4,
												"sentences": [
													"How's your new job? Is it fun?"
												],
												"blankedWords": [
													"How's"
												]
											}
										]
									}
								]
							},
							{
								"setMarker": "B",
								"setHeading": "WORK IT OUT",
								"setImage": null,
								"setAudioNumber": null,
								"setIgnore": false,
								"exerciseType": "word bank",
								"textMode": "full article",
								"exerciseInstruction": "Complete the table with ’s, is or isn’t.",
								"textContents": [
									{
										"paragraphOrdinal": 1,
										"paragraphTitle": "WORK IT OUT",
										"paragraphSubtitles": [
											"Simple present be: he, she, it"
										],
										"paragraphContents": [
											"Positive: He/She/It's nice.",
											"Negative: He/She/It isn’t nice.",
											"Question: Is he/she/it fun?"
										]
									}
								],
								"exercisesWordBank": [
									{
										"sentenceOrdinal": 1,
										"paragraphOrdinal": 1,
										"exerciseQuestion": null,
										"exerciseMaxAnswer": null,
										"exerciseMinAnswer": null,
										"exerciseAnswers": null,
										"LKUs": [
											"be"
										],
										"context": "textContents"
									}
								]
							},
							{
								"setMarker": "C",
								"setHeading": "",
								"setImage": null,
								"setAudioNumber": null,
								"setIgnore": false,
								"exerciseType": "Grammar SB/without explanation",
								"grammarHub": true,
								"exerciseInstruction": "Complete the email with the words in the box.",
								"wordBank": [
									"he's",
									"is",
									"is",
									"is",
									"is",
									"isn't",
									"it's",
									"she's"
								],
								"exercises": [
									{
										"exerciseSentences": [
											{
												"sentenceOrdinal": 1,
												"sentences": [
													"Hi Tina!"
												],
												"blankedWords": []
											},
											{
												"sentenceOrdinal": 2,
