=== magnibruno/MacmillanJSONFiles/.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "This document is a JSON Schema for the structure of the JSON data that will be used to generate the content of the Macmillan Chapters. $comment is used to add comments to the schema. The comments are not used for validation purposes.",
  "type": "object",
  "properties": {
    "book": {
      "type": "string",
      "$comment": "This document is a JSON Schema for the structure of the JSON data that will be used to generate the content of the Macmillan Chapters."
    },
    "CEFRLevel": {
      "type": "string"
    },
    "dialect": {
      "type": "string"
    },
    "chapter": {
      "type": "object",
      "properties": {
        "chapterUnit": {
          "type": "integer"
        },
        "chapterTitle": {
          "type": "string"
        },
        "chapterQuote": {
          "type": "string"
        },
        "chapterFrontImage": {
          "type": "string"
        },
        "chapterObjectives": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sections": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "sectionNumber": {
                "type": "number"
              },
              "sectionTitle": {
                "type": "string"
              },
              "sectionObjective": {
                "type": "string"
              },
              "sectionSkills": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "skillType": {
                      "type": "string"
                    },
                    "skillName": {
                      "type": "string"
                    },
                    "skillTitle": {
                      "type": "string"
                    }
                  },
                  "required": ["skillType", "skillName", "skillTitle"]
                }
              },
              "hasReading": {
                "type": "boolean",
                "$comment": "POSSIBLE VALUES = true or false with no quotes."
              },
              "GKU": {
                "type": "string"
              },
              "sectionPart": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "partTitle": {
                      "type": "string"
                    },
                    "partImage": {
                      "type": "string"
                    },
                    "partSubTitle": {
                      "type": ["string", "null"]
                    },
                    "sets": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "setMarker": {
                            "type": "string"
                          },
                          "setHeading": {
                            "type": "string"
                          },
                          "textImage": {
                            "type": "string"
                          },
                          "setAudioNumber": {
                            "type": ["number", "null"]
                          },
                          "setIgnore": {
                            "type": "boolean",
                            "$comment": "POSSIBLE VALUES = true or false with no quotes."
                          },
                          "textMode": {
                            "type": "string"
                          },
                          "textParts": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "textTitle": {
                                  "type": "string"
                                },
                                "textSubtitles": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "textContent": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "properties": {
                                      "textParagraphOrdinal": {
                                        "type": "integer"
                                      },
                                      "paragraphTitle": {
                                        "type": ["string", "null"]
                                      },
                                      "paragraphSubtitle": {
                                        "type": ["array", "null"],
                                        "items": {
                                          "type": "string"
                                        }
                                      },
                                      "paragraphContent": {
                                        "type": "array",
                                        "items": {
                                          "type": "string"
                                        }
                                      }
                                    },
                                    "required": ["textParagraphOrdinal", "paragraphContent"]
                                  }
                                }
                              },
                              "required": ["textTitle", "textSubtitles", "textContent"]
                            }
                          },
                          "exerciseType": {
                            "type": "string"
                          },
                          "exerciseInstruction": {
                            "type": ["string", "null"]
                          },
                          "exerciseQuestion": {
                            "type": "string"
                          },
                          "exerciseMaxAnswer": {
                            "type": "string"
                          },
                          "exerciseMinAnswer": {
                            "type": "string"
                          },
                          "LKUs": {
                            "type": "array",
                            "items": {
                              "type": "string"
                            }
                          },
                          "exercises": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "sentenceOrdinal": {
                                  "type": "integer"
                                },
                                "exerciseQuestion": {
                                  "type": "string"
                                },
                                "exerciseAnswer": {
                                  "type": "string"
                                },
                                "exerciseMaxAnswer": {
                                  "type": "string"
                                },
                                "exerciseMinAnswer": {
                                  "type": "string"
                                },
                                "LKUs": {
                                  "type": ["array", "string"],
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "sentenceAnswerOptions": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                },
                                "context": {
                                  "type": "string"
                                }
                              },
                              "required": ["sentenceOrdinal", "exerciseQuestion", "exerciseAnswer", "LKUs"]
                            }
                          },
                          "explanationBox": {
                            "type": "array",
                            "items": {
                              "type": "object",
                              "properties": {
                                "explanationTitle": {
                                  "type": "string"
                                },
                                "explanationContent": {
                                  "type": "array",
                                  "items": {
                                    "type": "string"
                                  }
                                }
                              },
                              "required": ["explanationTitle", "explanationContent"]
                            }
                          }
                        },
                        "required": ["setMarker", "setHeading", "textParts", "exerciseType"]
                      }
                    }
                  },
                  "required": ["partTitle", "partImage", "sets"]
                }
              }
            },
            "required": ["sectionNumber", "sectionTitle", "sectionObjective", "sectionSkills", "hasReading"]
          }
        }
      },
      "required": ["chapterUnit", "chapterTitle", "chapterQuote", "chapterFrontImage", "chapterObjectives", "sections"]
    }
  },
  "required": ["book", "CEFRLevel", "dialect", "chapter"]
}

=== magnibruno/MacmillanJSONFiles/validatedJSONContent/A1Unit1ReadingValid.json
{
	"book": "Language Hub",
	"CEFRLevel": "A1",
	"dialect": "American",
	"chapter": {
		"chapterUnit": 1,
		"chapterTitle": "Nice to meet you!",
		"chapterQuote": "The language of friendship is not words but meanings. Henry David Thoreau",
		"chapterFrontImage": "",
		"chapterObjectives": [
			"talk about where you're from'",
			"introduce a friend",
			"greet people",
			"fill in a form"
		],
		"sections": [
			{
				"sectionNumber": 1.1,
				"sectionTitle": "Say hello",
				"sectionObjective": "Talk about where you're from",
				"sectionSkills": [
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "countries"
					},
					{
						"skillType": "P",
						"skillName": "Pronunciation",
						"skillTitle": "syllables and syllable stress"
					},
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "numbers 0-10"
					},
					{
						"skillType": "G",
						"skillName": "Grammar",
						"skillTitle": "present simple be: I, you"
					}
				],
				"hasReading": false
			},
			{
				"sectionNumber": 1.2,
				"sectionTitle": "What’s your job?",
				"sectionObjective": "Introduce a friend",
				"sectionSkills": [
					{
						"skillType": "V",
						"skillName": "Vocabulary",
						"skillTitle": "jobs"
					},
					{
						"skillType": "S",
						"skillName": "Reading",
						"skillTitle": "identifying personal pronouns"
					},
					{
						"skillType": "G",
						"skillName": "Grammar",
						"skillTitle": "simple present be: he, she, it"
					},
					{
						"skillType": "P",
						"skillName": "Pronunciation",
						"skillTitle": "contractions with be"
					}
				],
				"hasReading": true,
				"GKU": "Language_Hub_A1_Unit1_Lesson1_2",
				"sectionPart": [
					{
						"partTitle": "READING",
						"partImage": "",
						"partSubTitle": null,
						"sets": [
							{
								"setMarker": "A",
								"setHeading": "READ FOR GIST",
								"textImage": "",
								"setAudioNumber": null,
								"setIgnore": false,
								"textMode": "full article",
								"textParts": [
									{
										"textTitle": "New job!",
										"textSubtitles": [
											"To: fashionista@mailhub.com",
											"From: em173@design.nett"
										],
										"textContent": [
											{
												"textParagraphOrdinal": 1,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"Hi Emma,",
													"How’s your new job? Is it fun? Is your manager nice? Please tell me all about it!",
													"Keira"
												]
											},
											{
												"textParagraphOrdinal": 2,
												"paragraphTitle": "RE: New job!",
												"paragraphSubtitle": [
													"To: em173@design.nett",
													"From: fashionista@mailhub.com"
												],
												"paragraphContent": [
													"Hi Keira,",
													"Today is my first day in my new job! I’m on the design team. It’s a small team with five people. My manager isn’t very friendly, but she’s OK. Her name is Amanda and she’s from Brazil."
												]
											},
											{
												"textParagraphOrdinal": 3,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"My colleague Anton is nice. He’s new today, too. I’m not very busy because it’s my first day.",
													"How are you?",
													"Emma",
													"P.S. Here’s a photo of me in my new job as a designer."
												]
											}
										]
									}
								],
								"exerciseType": "highlight",
								"exerciseInstruction": "Read the emails.",
								"exercises": [
									{
										"sentenceOrdinal": 1,
										"exerciseQuestion": "What is Emma’s new job?",
										"exerciseMaxAnswer": "Here’s a photo of me in my new job as a designer.",
										"exerciseMinAnswer": "a designer.",
										"exerciseAnswer": "a designer.",
										"LKUs": [
											"job",
											"designer"
										]
									}
								]								
							},
							{
								"setMarker": "B",
								"setHeading": "READ FOR DETAIL",
								"textImage": "",
								"setAudioNumber": null,
								"setIgnore": false,
								"textMode": "full article",
								"textParts": [
									{
										"textTitle": "New job!",
										"textSubtitles": [
											"To: fashionista@mailhub.com",
											"From: em173@design.nett"
										],
										"textContent": [
											{
												"textParagraphOrdinal": 1,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"Hi Emma,",
													"How’s your new job? Is it fun? Is your manager nice? Please tell me all about it!",
													"Keira"
												]
											},
											{
												"textParagraphOrdinal": 2,
												"paragraphTitle": "RE: New job!",
												"paragraphSubtitle": [
													"To: em173@design.nett",
													"From: fashionista@mailhub.com"
												],
												"paragraphContent": [
													"Hi Keira,",
													"Today is my first day in my new job! I’m on the design team. It’s a small team with five people. My manager isn’t very friendly, but she’s OK. Her name is Amanda and she’s from Brazil."
												]
											},
											{
												"textParagraphOrdinal": 3,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"My colleague Anton is nice. He’s new today, too. I’m not very busy because it’s my first day.",
													"How are you?",
													"Emma",
													"P.S. Here’s a photo of me in my new job as a designer."
												]
											}
										]
									}
								],
								"exerciseType": "multiple choice",
								"exerciseInstruction": "Read the emails again. Choose the correct answer.",
								"exercises": [
									{
										"sentenceOrdinal": 1,
										"exerciseQuestion": "Who is in a new job?",
										"exerciseAnswer": "Emma",
										"LKUs": [
											"job"
										],
										"sentenceAnswerOptions": [
											"Keira",
											"Emma"
										],
										"context": "textParts"
									},
									{
										"sentenceOrdinal": 2,
										"exerciseQuestion": "Is she on a small or big team?",
										"exerciseAnswer": "small",
										"LKUs": [
											"small",
											"team"
										],
										"sentenceAnswerOptions": [
											"small",
											"big"
										],
										"context": "textParts"
									},
									{
										"sentenceOrdinal": 3,
										"exerciseQuestion": "Is her manager friendly?",
										"exerciseAnswer": "Her manager isn't very friendly.",
										"LKUs": [
											"manager",
											"friendly"
										],
										"sentenceAnswerOptions": [
											"Her manager isn't very friendly.",
											"Her manager is very friendly."
										],
										"context": "textParts"
									},
									{
										"sentenceOrdinal": 4,
										"exerciseQuestion": "Where is her manager from?",
										"exerciseAnswer": "Brazil",
										"LKUs": [
											"manager",
											"from"
										],
										"sentenceAnswerOptions": [
											"Brazil",
											"Canada"
										],
										"context": "textParts"
									},
									{
										"sentenceOrdinal": 5,
										"exerciseQuestion": "Is Anton new?",
										"exerciseAnswer": "Anton is new.",
										"LKUs": "new",
										"sentenceAnswerOptions": [
											"Anton is new.",
											"Anton isn't new."
										],
										"context": "textParts"
									}
								],
								"explanationBox": [
									{
										"explanationTitle": "Identifying personal pronouns",
										"explanationContent": [
											"Pronouns talk about a noun.",
											"My colleague Anton is nice. He’s newtoday too."
										]
									}
								]
							},
							{
								"setMarker": "C",
								"setHeading": "READ FOR DETAILED UNDERSTANDING",
								"textImage": "",
								"setAudioNumber": null,
								"setIgnore": false,
								"textMode": "full article",
								"textParts": [
									{
										"textTitle": "New job!",
										"textSubtitles": [
											"To: fashionista@mailhub.com",
											"From: em173@design.nett"
										],
										"textContent": [
											{
												"textParagraphOrdinal": 1,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"Hi Emma,",
													"How’s your new job? Is it fun? Is your manager nice? Please tell me all about it!",
													"Keira"
												]
											},
											{
												"textParagraphOrdinal": 2,
												"paragraphTitle": "RE: New job!",
												"paragraphSubtitle": [
													"To: em173@design.nett",
													"From: fashionista@mailhub.com"
												],
												"paragraphContent": [
													"Hi Keira,",
													"Today is my first day in my new job! I’m on the design team. It’s a small team with five people. My manager isn’t very friendly, but she’s OK. Her name is Amanda and she’s from Brazil."
												]
											},
											{
												"textParagraphOrdinal": 3,
												"paragraphTitle": null,
												"paragraphSubtitle": null,
												"paragraphContent": [
													"My colleague Anton is nice. He’s new today, too. I’m not very busy because it’s my first day.",
													"How are you?",
													"Emma",
													"P.S. Here’s a photo of me in my new job as a designer."
												]
											}
										]
									}
								],
								"exerciseType": "multiple choice",
								"exerciseInstruction": "What do the words in bold refer to?",
								"exercises": [
									{
										"sentenceOrdinal": 1,
										"exerciseQuestion": "How’s your new job? Is it fun?",
										"wordinBold": "it",
